services:
  db:
    image: postgres:15
    container_name: tienda_profe_db
    environment:
      POSTGRES_DB: tienda_db
      POSTGRES_PASSWORD: admin_password
    ports:
      - "5432:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d

  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgres://web_dashboard_user:dashboard_pass_2026@db:5432/tienda_db"
    depends_on:
      - db